server:
  port: 7070

preference:
  website:
#    session:
#      blogger-id: bloggerId
#      blogger-name: bloggerName
#      login-signal: bloggerLoginSignal
#      error-msg: errorMsg
#      owner-id: pageOwnerBloggerId
#      owner-name: pageOwnerBloggerName