server:
  port: 7070

app:
  name: blogos

# 直接依赖 blog-service-impl 项目，而不是 rpc 的方式，因此需要将配置移到这里
spring:
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    serialization:
  #      write_dates_as_timestamps: false
  #    default-property-inclusion: NON_NULL
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 128Mb
      file-size-threshold: 5Mb
  messages:
    basename: messages
    cache-seconds: 3600

dubbo:
  application:
    name: blogos-api
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 3000
