spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: NON_NULL
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 128Mb
  messages:
    basename: i18n/messages
    cache-seconds: 3600
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      maxTotal: 1024
      maxIdle: 200
      maxWait: 1000
      testOnBorrow: true
      testOnReturn: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: wall
    maxActive: 100
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 9090

app:
  name: blogos-service

mybatis:
  mapperLocations: classpath:mapper/*/*.xml

  config: classpath:mybatis-config.xml





redis:
  key:
    expire: 2592000
  token:
    expire-day: 30


jisu:
  appkey: 5171de6ae9fd57a6
  smssend-url: http://api.jisuapi.com/sms/send

preference:
  default:
    blog-count: 10
    comment-count: 10
    link-count: 10
    picture-count: 10
    collect-count: 10
    category-count: 10
    label-count: 10
    blog-category-id: 1
    url-condition-split-character: \u002C
  website:
    manager-id: 1
    manager-email: duan_jia_ning@163.com
    page-nav-pos: 0
    sender-mail: 2213994603@qq.com
    sender-mail-password: athupcbmeyvvdjif
    active-blogger-count: 20
    addr: 127.0.0.1:8080
  file:
    image-root-path: /usr/duan/blog/blogger/image
    patch-import-blog-temp-path: /usr/duan/blog/blogger/image
    patch-download-blog-temp-path: /usr/duan/blog/temp/blog-patch-download
    lucene-index-dir: /usr/duan/blog/lucene
  db:
    string-filed-split-character-for-number: \u0020
    string-filed-split-character-for-string: \u0020